#import "../../../utils.typ"
#import utils: *

Let $F: cat(C) arrow macron(cat(C))$ be a functor from a small factor to its Cayley representation, in which $F$ maps objects $F: C |-> {"morphisms ending at" C}$ and maps morphisms $F: f |-> {"functions generated by postcomposition with f"}$, as shown in the diagram below.

#align(center)[#image("ex13_1.excalidraw.png", width:60%)]

To show $cat(C) tilde.eq macron(cat(C))$, it suffices to show that $F$ is bijective in objects and that the functors are full and faithful. $F$ is obviously bijective in objects, since each codomain object is defined in terms of the ending of morphisms, which is distinct. For every morphism in the homset $f in Hom_(cat(C))(A, B)$, there is one morphism  $macron(f) in Hom_(cat(macron(C)))(A, B)$ by construction, so $F$ is full. To show that $F$ is faithful, suppose that $g, g' in Hom_(cat(C))(B, C)$ such that  $g eq.not g'$. $g$ acts on each element in $macron(B)$ by precomposition, and likewise for g'. Because $g eq.not g'$, for any arbitrary $f in macron(B)$, $g compose f eq.not g' compose f$. Because their actions on arbitrary elements are distinct, as functions they are not equal $macron(g) eq.not macron(g')$, so $F$ is faithful, and therefore $cat(C)$ and $macron(cat(C))$ are isomorphic.