#import "../../../utils.typ"
#import utils: *

Given arbitrary category $cat(C)$ with objects
$c, x, x'$ and morphisms as shown in the top left category of the diagram below,
the slice category can be generated by 1) taking the opposite category, 2) 
taking the slice of this opposite category, and 3) taking the opposite. This 
is equal to the coslice category $cat(C) \/ c.$

#align(center, image("ex6_1.excalidraw.png", width: 50%))